site_name: Opseen ERP User Guide
site_url: https://user-guide.readthedocs.io

nav:
  - Home: index.md
  - Finance:
      - Chart of Accounts: 01-chart-of-accounts.md

theme:
  name: readthedocs

docs_dir: docs
